package sma.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;
import sma.Model.Car.CarInterface;
import sma.Model.Light.LightInterface;
import utils.Constants;

/**
 *
 */
public class RoadPanel extends JPanel {

    private Image back;
    private Rectangle rectangle;

    /**
     *
     */
    public static int FRAMECOUNTER = 0;
    
    /**
     * Creates new form RoadPanel
     */
    public RoadPanel() {
        super(true);
        initComponents();
        
        this.back = GUIUtils.getInstance().loadImage("road");
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        FRAMECOUNTER = (FRAMECOUNTER+1)%Constants.FRAMERATE;
        
        Graphics2D g2 = (Graphics2D)g;
        
        BufferedImage bufferedImage = new BufferedImage(400, 400, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = bufferedImage.createGraphics();
        
        if (back != null)
            g2d.drawImage(back, 0, 0, null);
        
        if (rectangle == null)
            rectangle = new Rectangle(0, 0, getSize().width/2, getSize().height/2);
        
        for (LightInterface light : MainWindow.instance().getControllerAgent().getLights()) {
            GUIUtils.getInstance().drawLight(g2d, rectangle, light);
        }
        
        for (CarInterface car : MainWindow.instance().getControllerAgent().getCars()) {
            GUIUtils.getInstance().drawCar(g2d, rectangle, car);
        }
    
        g2.drawImage(bufferedImage, 0, 0, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
